import type { Recipe } from '../types';
import { generateId } from './helpers';

const now = new Date().toISOString();

export const SEED_RECIPES: Recipe[] = [
  {
    id: generateId(),
    title: 'Spaghetti Bolognese',
    description: 'A hearty Italian classic with a rich beef and tomato sauce that the whole family loves.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Spaghetti', quantity: 400, unit: 'g' },
      { id: generateId(), name: 'Beef mince', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Tinned tomatoes', quantity: 2, unit: 'tin' },
      { id: generateId(), name: 'Onion', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 3, unit: 'pieces' },
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tbsp' },
    ],
    steps: [
      'Heat olive oil in a large pan over medium heat.',
      'Finely chop the onion and garlic, then sauté until softened (5 mins).',
      'Add the beef mince and cook until browned, breaking it up as you go.',
      'Stir in the tinned tomatoes, season well, and simmer for 20 minutes.',
      'Cook spaghetti according to packet instructions. Serve with the bolognese sauce.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: 'Improves the next day! Freeze any leftovers.',
    source_url: '',
    tags: ['family-favourite', 'batch-cook'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Overnight Oats',
    description: 'Creamy, no-cook oats prepared the night before for a quick and nutritious breakfast.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Rolled oats', quantity: 80, unit: 'g' },
      { id: generateId(), name: 'Milk', quantity: 200, unit: 'ml' },
      { id: generateId(), name: 'Greek yoghurt', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Banana', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Honey', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Mix oats, milk, and yoghurt in a jar or bowl.',
      'Stir in honey, cover, and refrigerate overnight.',
      'Serve topped with sliced banana and any extra toppings you like.',
    ],
    meal_type: ['breakfast', 'baby'],
    servings: 2,
    notes: 'Can be prepared up to 3 days ahead. Great for baby without the honey.',
    source_url: '',
    tags: ['quick', 'vegetarian', 'batch-cook'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Chicken & Vegetable Stir-Fry',
    description: 'A quick, colourful stir-fry loaded with vegetables and tender chicken breast.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Chicken breast', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Broccoli', quantity: 200, unit: 'g' },
      { id: generateId(), name: 'Bell pepper', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Soy sauce', quantity: 3, unit: 'tbsp' },
      { id: generateId(), name: 'Sesame oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Ginger', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Rice', quantity: 300, unit: 'g' },
    ],
    steps: [
      'Cook rice according to packet instructions.',
      'Slice chicken into thin strips and season lightly.',
      'Heat sesame oil in a wok or large frying pan on high heat.',
      'Stir-fry chicken until golden (5–6 mins), then set aside.',
      'Add garlic, ginger, and vegetables to the wok; stir-fry for 3–4 mins.',
      'Return chicken to the pan, add soy sauce, toss to combine, and serve over rice.',
    ],
    meal_type: ['lunch', 'dinner'],
    servings: 4,
    notes: 'Swap chicken for tofu for a vegetarian version.',
    source_url: '',
    tags: ['quick', 'healthy'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Tomato Soup',
    description: 'Velvety, warming tomato soup made from roasted tomatoes. Perfect with crusty bread.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Tomatoes', quantity: 1, unit: 'kg' },
      { id: generateId(), name: 'Onion', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 3, unit: 'pieces' },
      { id: generateId(), name: 'Vegetable stock', quantity: 500, unit: 'ml' },
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Basil', quantity: 1, unit: 'bunch' },
    ],
    steps: [
      'Preheat oven to 200°C. Halve tomatoes, place on a baking tray with onion and garlic.',
      'Drizzle with olive oil, season, and roast for 30 minutes until caramelised.',
      'Transfer roasted vegetables and any juices to a large saucepan.',
      'Add stock and blend until smooth with a stick blender.',
      'Simmer for 5 minutes, adjust seasoning, and serve with fresh basil.',
    ],
    meal_type: ['lunch'],
    servings: 4,
    notes: 'Freezes well. Add a swirl of cream for a richer finish.',
    source_url: '',
    tags: ['vegetarian', 'batch-cook'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Banana Porridge',
    description: 'Smooth, creamy porridge with mashed banana — perfect for babies and toddlers too.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Rolled oats', quantity: 50, unit: 'g' },
      { id: generateId(), name: 'Whole milk', quantity: 200, unit: 'ml' },
      { id: generateId(), name: 'Banana', quantity: 1, unit: 'pieces' },
    ],
    steps: [
      'Place oats and milk in a saucepan. Cook over medium heat, stirring, for 4–5 minutes.',
      'Mash the banana and stir into the porridge.',
      'Serve immediately, cooled slightly for little ones.',
    ],
    meal_type: ['breakfast', 'baby'],
    servings: 2,
    notes: 'No salt or sugar needed for babies. Add a pinch of cinnamon for flavour.',
    source_url: '',
    tags: ['baby-friendly', 'vegetarian', 'quick'],
    created_at: now,
    updated_at: now,
  },
];
