import type { Recipe } from '../types';
import { generateId } from './helpers';

const now = new Date().toISOString();

export const SEED_RECIPES: Recipe[] = [
  {
    id: generateId(),
    title: 'Gnocchi with Pesto & Green Beans',
    description: "A family-friendly tray-bake supper that's low on cost and cooked on a single tray.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sweet peppers', quantity: 3, unit: 'pieces' },
      { id: generateId(), name: 'Olive oil', quantity: 1.5, unit: 'tbsp' },
      { id: generateId(), name: 'Gnocchi', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Green beans', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Green pesto', quantity: 145, unit: 'g' },
    ],
    steps: [
      'Preheat the oven to 200°C (gas mark 6). Deseed the sweet peppers and cut into strips. Toss with 1 tbsp of the oil in a roasting tin and roast for 15 minutes.',
      'Put the gnocchi in a heatproof bowl and cover with just-boiled water from the kettle. Set aside for 3 minutes, then drain.',
      'Trim the ends of the green beans. Add the gnocchi and beans to the roasting tin, sprinkle over the remaining ½ tbsp oil, season, and roast for a further 10 minutes.',
      'As soon as the tin comes out of the oven, stir the pesto through the gnocchi, peppers and beans. Divide between plates with wild rocket and shavings of Parmigiano Reggiano, if liked.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Optional to serve: wild rocket leaves and Parmigiano Reggiano shavings. Cook's tip — swap the green pesto for red chilli pesto and add some cherry tomatoes for a different flavour.",
    source_url: '',
    tags: ['vegetarian', 'one-tray', 'quick', 'family-favourite'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Salmon & Avocado Noodles',
    description: 'A quick midweek bowl of egg noodles, salmon and avocado with a salty-sweet soy-ginger dressing.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Edamame beans (frozen)', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Salmon fillets', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Egg noodles', quantity: 275, unit: 'g' },
      { id: generateId(), name: 'Avocado', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Salad onions', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Soy sauce', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Mirin', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Maple syrup', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Toasted sesame oil', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Ginger', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Shichimi togarashi', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat the grill to high. Cook the edamame beans according to pack instructions, drain and set aside.',
      'Make the soy-ginger dressing by mixing the soy sauce, mirin, maple syrup, sesame oil and grated ginger in a small bowl.',
      'Arrange the salmon, skin-side down, on a foil-lined baking tray. Spoon over 2 tsp of the dressing. Grill for 6–8 minutes, until the fish is opaque and flakes easily.',
      'Meanwhile, cook the egg noodles according to pack instructions and divide between shallow bowls.',
      'Slice the avocado and finely slice the salad onions. Top each bowl with a salmon fillet, the edamame beans, avocado and salad onions. Spoon over the remaining dressing and sprinkle with shichimi togarashi, if liked.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — Mirin is a Japanese rice wine, similar to sake but lower in alcohol and sweeter. If you don't have any, substitute a splash of sherry or rice vinegar. The shichimi togarashi is optional.",
    source_url: '',
    tags: ['quick', 'fish', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Smoky Barbecue Beans, Sweet Potato Fries & Guac',
    description: 'Smoky tomatoey beans with crispy sweet potato wedges and fresh guacamole. Vegan and low carbon impact.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sweet potato', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Onion', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Courgette', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Haricot beans', quantity: 240, unit: 'g' },
      { id: generateId(), name: 'Smoked paprika', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Chilli flakes', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Passata', quantity: 200, unit: 'g' },
      { id: generateId(), name: 'Balsamic vinegar', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Maple syrup', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Fresh coriander', quantity: 1, unit: 'bunch' },
      { id: generateId(), name: 'Lime', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Avocado', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Preheat the oven to 220°C (fan 200°C / gas mark 7) and line a baking tray with parchment. Cut the sweet potato into 2 cm thick wedges, toss with ½ tbsp oil and a pinch of salt and pepper on the tray, and roast for 20–25 minutes until soft and golden.',
      'Meanwhile, finely chop or crush the garlic. Finely slice three-quarters of the onion and finely dice the rest. Thinly slice the courgette into half-moons. Drain and rinse the haricot beans.',
      'Heat a large saucepan with the remaining ½ tbsp oil over medium heat. Add the garlic and sliced onion and cook for 3 minutes. Season, then add the courgette, paprika and chilli flakes (to taste) and cook for a further 3 minutes.',
      'Add the beans, passata, balsamic vinegar and maple syrup. Simmer for 8–10 minutes, until the sauce thickens.',
      'Roughly chop the coriander and halve the lime. Mash the avocado in a small bowl, then mix in the diced onion, coriander and a squeeze of lime juice. Season to taste.',
      'Serve the barbecue beans with the guacamole and sweet potato wedges. Garnish with the remaining lime, cut into wedges.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: 'Halve the ingredients to serve 1. The dish is vegan as written.',
    source_url: '',
    tags: ['vegan', 'midweek', 'low-carbon'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Chilli Crab & Toasted Corn Linguine',
    description: 'Speedy pasta with charred sweetcorn, mild red chilli, parsley and crab — ready in 20 minutes.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sweetcorn (frozen)', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Dried linguine', quantity: 180, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 2.5, unit: 'tbsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Mild red chilli', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Flat leaf parsley', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Crab meat (50/50 white & brown)', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Unwaxed lemon', quantity: 0.5, unit: 'pieces' },
    ],
    steps: [
      'Heat a medium-large nonstick frying pan over a high heat. Add the corn and dry-fry, stirring regularly, for 5 minutes until lightly charred in places and piping hot. Tip into a bowl and set aside. Meanwhile, cook the pasta in a large saucepan of salted boiling water for 1 minute less than the pack instructions.',
      'Five minutes before the pasta is ready, return the frying pan to a medium heat with the oil, finely chopped garlic, deseeded and finely chopped chilli, and finely chopped parsley. Cook gently for 2 minutes, then stir in the crab and warm everything through.',
      'Scoop out a mugful of the pasta cooking water, then drain the pasta and add to the frying pan with a glug of the cooking water. Toss over the heat with the charred corn and the lemon zest and juice until piping hot. Divide between plates and serve straight away.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — 50/50 crab is a mix of white and brown crabmeat. If you prefer a milder crab flavour, use all-white meat.",
    source_url: '',
    tags: ['quick', 'fish', 'pasta'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Salmon & Watercress Spaghetti',
    description: 'A tub of watercress tzatziki creates an almost instant sauce for this speedy pasta dish.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Dried spaghetti', quantity: 180, unit: 'g' },
      { id: generateId(), name: 'Purple sprouting broccoli', quantity: 230, unit: 'g' },
      { id: generateId(), name: 'Scottish poached salmon fillets', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Watercress tzatziki', quantity: 170, unit: 'g' },
      { id: generateId(), name: 'Unwaxed lemon', quantity: 0.5, unit: 'pieces' },
      { id: generateId(), name: 'Parmigiano Reggiano', quantity: 10, unit: 'g' },
    ],
    steps: [
      'Bring a large saucepan of salted water to the boil. Add the spaghetti and simmer for a minute less than pack instructions, adding the broccoli (cut into 3–4 cm pieces) to the pan for the final 3 minutes of cooking time. Before draining, scoop out a mugful of the cooking water. Meanwhile, flake the salmon and remove the skin.',
      'Tip the drained pasta back into the pan (off the heat). Add the flaked salmon, tzatziki, lemon zest and a squeeze of juice, the cheese and 3 tbsp of the pasta cooking water. Toss together with tongs to combine and serve with extra grated cheese.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: 'Boost fibre by using wholewheat spaghetti and add some frozen peas with the broccoli, if liked.',
    source_url: '',
    tags: ['quick', 'fish', 'pasta', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Cheddar & Leek Orzotto',
    description: "A pleasingly simple twist on risotto that's quicker to make but just as gratifying as the original.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Leek (large, ~250g)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Unsalted butter', quantity: 20, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Orzo pasta', quantity: 150, unit: 'g' },
      { id: generateId(), name: 'Chicken or vegetable stock', quantity: 500, unit: 'ml' },
      { id: generateId(), name: 'Petits pois (frozen)', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Mature cheddar', quantity: 80, unit: 'g' },
    ],
    steps: [
      'Halve the leek lengthways, then halve again into quarters and finely slice. Heat the butter and olive oil in a medium-large saucepan over a medium-high heat. Add the leek, finely chopped garlic and a pinch of salt and cook, stirring regularly, for 5 minutes until soft but without any colour.',
      'Add the orzo to the pan and stir through the leek. Cook, stirring, for 2 minutes. Add 400 ml of the stock, bring to the boil, then reduce to a gentle simmer. Cook for about 4 minutes, stirring regularly, then stir in the peas. Cook for another 4 minutes, adding more stock if it looks dry (it should be a loose consistency). The orzo is ready when tender but with just a little bite.',
      'Take off the heat and stir in half of the cheddar, then let stand for 2 minutes. Sprinkle the remaining cheese over the top and serve with a grinding of black pepper.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — Use fresh stock if you can; its flavour really comes through in the orzotto.",
    source_url: '',
    tags: ['vegetarian', 'quick', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Courgette, Chickpea & Feta Pasta',
    description: 'A great-value, great-tasting weeknight pasta — the chickpeas pack in fibre and protein.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Olive oil', quantity: 3, unit: 'tbsp' },
      { id: generateId(), name: 'Courgettes', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 3, unit: 'pieces' },
      { id: generateId(), name: 'Chifferi rigati (or other short) pasta', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Chickpeas (tinned)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Lemon', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Chilli flakes', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Feta', quantity: 120, unit: 'g' },
      { id: generateId(), name: 'Basil', quantity: 1, unit: 'bunch' },
    ],
    steps: [
      'Heat the oil in a large frying pan over a medium-high heat. Add the thinly sliced courgettes and sliced garlic with a large pinch of salt. Fry for 10–12 minutes until tender and golden.',
      'Once the courgettes are turning golden, bring a large pan of salted water to the boil. Add the pasta and cook according to pack instructions. Scoop out a mugful of cooking water, then drain.',
      'Meanwhile, add the drained and rinsed chickpeas to the courgette pan, turn the heat up to high and fry for another 5 minutes. Stir in the drained pasta, 3 tbsp pasta cooking water, the lemon zest and the juice of ½ the lemon, and the chilli flakes. Toss together. Take off the heat and stir through the crumbled feta and shredded basil (if using). Season and serve immediately with freshly ground black pepper.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Cook's tip — chilli flakes vary in heat; add a little, taste, then add more. Sub in paprika to skip the heat. Basil is optional.",
    source_url: '',
    tags: ['vegetarian', 'pasta', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Conchiglie with Mushrooms & Spinach',
    description: 'A veg-packed pasta bake with porcini, chestnut mushrooms, wilted spinach and a creamy parmesan sauce.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Dried porcini mushrooms', quantity: 15, unit: 'g' },
      { id: generateId(), name: 'Spinach (ready-washed)', quantity: 235, unit: 'g' },
      { id: generateId(), name: 'Conchiglie rigate pasta', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Echalion shallots', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Chestnut mushrooms', quantity: 250, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Double cream', quantity: 6, unit: 'tbsp' },
      { id: generateId(), name: 'Parmigiano Reggiano', quantity: 60, unit: 'g' },
    ],
    steps: [
      'Preheat the grill to high and put an oven shelf in the top third of the oven. Boil a kettle. Put the dried porcini in a heatproof bowl and cover with 300 ml just-boiled water; set aside. Put the spinach in a large mixing bowl and pour over enough just-boiled water to wilt. Drain through a sieve, rinse under the cold tap, squeeze out the excess liquid and pat dry with kitchen paper.',
      'Bring a large saucepan of water to the boil and cook the pasta for 1 minute less than pack instructions. In a separate large, shallow casserole, heat the oil over medium-high heat. Add the finely diced shallots, sliced chestnut mushrooms, crushed garlic and a pinch of salt. Cover with a lid and sweat for 5 minutes, stirring occasionally. Uncover and fry for another 5 minutes.',
      'Lift the porcini out of the soaking liquid, squeezing any excess back into the bowl (reserve the liquid). Finely chop the porcini and roughly chop the spinach, then stir both into the casserole. Add 200 ml of the mushroom soaking liquid (leaving any sediment behind) and the cream. Drain the pasta and tip into the casserole with ⅔ of the parmesan. Season and stir together over the heat for 1 minute.',
      'Scatter over the remaining cheese and grill for 2–3 minutes until golden. Stand for 2 minutes before serving in bowls.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Cook's tip — Blanching and drying the spinach first stops the sauce becoming watery.",
    source_url: '',
    tags: ['vegetarian', 'pasta'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Smoky Grains with Courgette & Butter Beans',
    description: 'An easy vegan supper of charred courgette ribbons, crispy paprika butter beans and Spanish-style grains, lifted with mint and lemon.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Courgettes (medium)', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Butter beans (tinned)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Hot smoked paprika', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Spanish-style grains & rice pouch', quantity: 1, unit: 'pack' },
      { id: generateId(), name: 'Lemon', quantity: 0.5, unit: 'pieces' },
      { id: generateId(), name: 'Mint', quantity: 1, unit: 'bunch' },
    ],
    steps: [
      'Heat a griddle or large frying pan over a high heat. Slice the courgettes lengthways into thin strips. Put 1 tbsp of the oil in a mixing bowl and toss the courgette strips to coat. Fry in batches for 2 minutes on each side until soft and golden, then season lightly. Keep the mixing bowl with any leftover oil.',
      'Add the remaining 1 tbsp oil and the finely grated garlic to the mixing bowl, then add the drained, rinsed and patted-dry butter beans and coat them in the oil and garlic. Sprinkle with the paprika, then fry the beans in the pan for 5–6 minutes until golden. Reserve the bowl with any leftover oil and garlic.',
      'Heat the grains according to pack instructions. Squeeze the juice of ¼ of the lemon into the mixing bowl, then toss in the warm grains. Stir through the shredded mint leaves (about 20) and the crispy butter beans. Divide between plates, arrange the courgette strips on top, and serve with the remaining lemon, cut into wedges.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — for extra protein and crunch, add toasted nuts or seeds. Pistachios or pumpkin seeds work brilliantly.",
    source_url: '',
    tags: ['vegan', 'quick', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Salmon with Citrus Slaw',
    description: 'Grilled salmon with a bright tangerine-and-soy slaw of beetroot, carrot, cabbage and red onion, finished with toasted pecans.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Pecans', quantity: 30, unit: 'g' },
      { id: generateId(), name: 'Tangerines', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Ginger', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Soy sauce (reduced salt)', quantity: 1.5, unit: 'tbsp' },
      { id: generateId(), name: 'Toasted sesame oil', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Salmon tail fillets', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Raw beetroot (~100g)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Carrot (small)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Pointed spring cabbage', quantity: 0.25, unit: 'pieces' },
      { id: generateId(), name: 'Red onion (small)', quantity: 0.5, unit: 'pieces' },
    ],
    steps: [
      'Preheat the oven to 180°C (gas mark 4). Roast the pecans for 5 minutes, then set aside. Meanwhile, mix the juice of 1 tangerine with the finely grated ginger, finely grated garlic, soy sauce and sesame oil. Use 2 tbsp of the dressing to marinate the salmon and set the rest aside.',
      'For the slaw, finely slice the trimmed and peeled beetroot into rounds, then cut into thin matchsticks. Put in a bowl with the grated or julienned carrot, shredded cabbage and finely sliced red onion. Peel the remaining tangerine, separate into segments, and cut each into thirds. Set everything aside.',
      'Turn the grill to high. Put the salmon (skin removed) on a foil-lined baking tray and grill for 5–6 minutes, until opaque and fully cooked. Toss the shredded vegetables with the remaining dressing, then toss through the pecans and tangerine pieces. Divide between plates and top with the salmon.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — a julienne peeler is really useful for making slaws. If cutting by hand, sharpen your knife first for neat, thin slices.",
    source_url: '',
    tags: ['fish', 'quick', 'midweek', 'healthy'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Tomato & Basil Pasta Salad',
    description: "A Sicilian-inspired pasta salad where fresh tomatoes form the base of the pesto. Use a vegetarian hard cheese if you prefer.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Basil', quantity: 25, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Toasted flaked almonds', quantity: 50, unit: 'g' },
      { id: generateId(), name: 'Salt', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Vine tomatoes', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Olive oil (extra virgin)', quantity: 4, unit: 'tbsp' },
      { id: generateId(), name: 'Lemon juice', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Fusilli (or other short pasta)', quantity: 350, unit: 'g' },
      { id: generateId(), name: 'Wild rocket', quantity: 45, unit: 'g' },
      { id: generateId(), name: 'Pecorino', quantity: 50, unit: 'g' },
    ],
    steps: [
      'Put the basil, roughly chopped garlic and almonds in a food processor with the salt. Whizz to a sticky paste. Roughly chop the tomatoes, then add two-thirds to the processor with the oil and lemon juice. Pulse together to a loose pesto, then tip into a large mixing bowl.',
      'Bring a large pan of salted water to the boil. Cook the pasta according to pack instructions, then drain. Toss the hot pasta and rocket through the pesto and allow to cool for 5 minutes.',
      'Add the remaining chopped tomatoes to the bowl with the shaved or grated pecorino and some extra toasted flaked almonds. Serve.',
    ],
    meal_type: ['lunch', 'dinner'],
    servings: 4,
    notes: 'Leftovers — pecorino is a mild, slightly salty sheep\'s-milk cheese. Use it as you would Parmigiano Reggiano.',
    source_url: '',
    tags: ['vegetarian', 'pasta', 'summer'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Thai-Style Salmon Curry',
    description: 'A warming one-pan curry ready in half an hour, using frozen Thai green herb portions for a quick aromatic base.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sunflower oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Thai green herb portions (frozen)', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Coconut milk (reduced fat)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Fish sauce', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Maple syrup', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Salmon fillets', quantity: 4, unit: 'pieces' },
      { id: generateId(), name: 'Sugar snap peas', quantity: 320, unit: 'g' },
      { id: generateId(), name: 'Lime', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Coriander', quantity: 1, unit: 'bunch' },
      { id: generateId(), name: 'Rice (to serve)', quantity: 300, unit: 'g' },
    ],
    steps: [
      'Heat the oil in a large sauté pan or shallow casserole dish over a medium-high heat. Add the Thai green herb portions and cook, stirring, for 3–4 minutes. Add the coconut milk, fish sauce and maple syrup, and simmer for 5–6 minutes.',
      'Turn the heat to medium-low. Add the salmon fillets (skin removed), skinned-side up, cover with a lid and simmer gently for 8–10 minutes. Turn the fillets over, add the sugar snaps, cover again, and simmer for a final 4 minutes, until the salmon is opaque and flakes easily.',
      'Allow to stand for 1 minute, then squeeze over the juice of ½ the lime. Serve with the rest of the lime cut into wedges, coriander leaves and steamed rice.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: 'Leftovers — fish sauce stores well in the fridge. Use it to add umami to curries, stews and salad dressings, or as an anchovy substitute in pasta sauces. Caster sugar can replace the maple syrup.',
    source_url: '',
    tags: ['fish', 'midweek', 'curry'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Sweet Chilli Salmon Chopped Salad',
    description: 'A zingy no-cook salad with hot-smoked sweet chilli salmon, ready in under 20 minutes.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Romaine lettuce', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Avocado (small)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Cucumber', quantity: 200, unit: 'g' },
      { id: generateId(), name: 'Red onion', quantity: 0.5, unit: 'pieces' },
      { id: generateId(), name: 'Cooked quinoa (red & white)', quantity: 250, unit: 'g' },
      { id: generateId(), name: 'Coriander', quantity: 1, unit: 'bunch' },
      { id: generateId(), name: 'Hot smoked salmon (sweet chilli)', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Soy sauce', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Balsamic vinegar', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Clear honey', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Toasted sesame oil', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
    ],
    steps: [
      'In a large mixing bowl, whisk together the dressing: soy sauce, olive oil, balsamic vinegar, honey, sesame oil and the finely grated garlic (garlic is optional).',
      'Shred the romaine, finely chop the avocado, halve and finely slice the cucumber, finely slice the red onion and roughly chop the coriander.',
      'Add the lettuce, avocado, cucumber, red onion, quinoa and coriander (if using) to the bowl and toss everything together. Divide between plates and flake the salmon over the top.',
    ],
    meal_type: ['lunch', 'dinner'],
    servings: 2,
    notes: 'Coriander and garlic in the dressing are optional. Use a veg peeler for cucumber ribbons if you prefer.',
    source_url: '',
    tags: ['fish', 'quick', 'no-cook', 'summer'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Teriyaki Salmon Noodles',
    description: "A veg-packed noodle bowl with hot-smoked teriyaki salmon, sugar snaps and a mayo-lime dressing — on the table in 20 minutes.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sugar snap peas', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Mayonnaise', quantity: 3, unit: 'tbsp' },
      { id: generateId(), name: 'Soy sauce', quantity: 1.5, unit: 'tbsp' },
      { id: generateId(), name: 'Lime', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Microwaveable rice noodles', quantity: 275, unit: 'g' },
      { id: generateId(), name: 'White cabbage', quantity: 150, unit: 'g' },
      { id: generateId(), name: 'Salad onions', quantity: 4, unit: 'pieces' },
      { id: generateId(), name: 'Hot smoked salmon (teriyaki)', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Chilli oil', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Bring a saucepan of salted water to the boil and blanch the sugar snaps for 2–3 minutes. Drain, refresh under cold running water and drain again. Meanwhile, in a large mixing bowl, whisk together the mayonnaise, soy sauce, lime juice and finely grated garlic.',
      'Heat the rice noodles according to pack instructions, then add to the mixing bowl along with the finely shredded cabbage, finely sliced salad onions and sugar snaps. Toss everything together to coat in the dressing and divide between plates.',
      'Remove the skin from the salmon and flake the fish over the noodles. Serve with a little chilli oil, if liked.',
    ],
    meal_type: ['lunch', 'dinner'],
    servings: 2,
    notes: 'Chilli oil is optional. Leftovers — use leftover white cabbage in a slaw with red onion and carrot, tossed with mayo and lemon juice.',
    source_url: '',
    tags: ['fish', 'quick', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Sausage Bake with Chimichurri',
    description: 'A plant-based traybake of charlotte potatoes, red onion and pepper with meat-free sausages, finished with a zingy chimichurri.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Charlotte potatoes', quantity: 700, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Red onions', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Red pepper (large)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Sweet smoked paprika', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Meat-free sausages', quantity: 8, unit: 'pieces' },
      { id: generateId(), name: 'Spinach or kale', quantity: 1, unit: 'bunch' },
      { id: generateId(), name: 'Chimichurri portions (frozen)', quantity: 100, unit: 'g' },
    ],
    steps: [
      'Preheat the oven to 200°C (gas mark 6). Cut the potatoes into bitesized pieces, toss with 1 tbsp of the oil on a large baking tray and roast for 15 minutes.',
      'Cut the red onions into thin wedges and the red pepper into strips. Add to the tray with the remaining 1 tbsp oil, sprinkle over the paprika, season and stir everything together. Nestle the sausages into the tray and roast for 20 minutes, stirring halfway through.',
      'Five minutes before the traybake is ready, toss through the spinach or kale (if using). At the same time, put the chimichurri portions in a microwaveable bowl, cover, and heat on full power for 2 minutes 30 seconds, stirring halfway through. Stand for 1 minute, then stir and serve with the sausages and vegetables.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: 'Spinach/kale is optional. Leftovers — chimichurri works with chicken or pork sausages too. The bake freezes for up to 2 months.',
    source_url: '',
    tags: ['vegan', 'one-tray', 'midweek', 'family-favourite'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Miso Mushroom Noodles',
    description: 'A vegan wok supper ready in a flash, packed with umami miso, mushrooms and udon noodles. 2 of your 5-a-day.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sunflower oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Mushroom stir fry mix', quantity: 400, unit: 'g' },
      { id: generateId(), name: 'Udon noodles (straight-to-wok)', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'White miso paste', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Balsamic vinegar', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Maple syrup', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Soy sauce (reduced salt)', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Toasted sesame oil', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
    ],
    steps: [
      'In a small bowl, mix the miso paste, balsamic vinegar, maple syrup, soy sauce, sesame oil and finely grated garlic with 2 tbsp water; set aside.',
      'Heat the oil in a large wok or frying pan over a high heat. When smoking hot, add the mushroom stir fry and fry for 5 minutes, stirring regularly.',
      'Add the miso sauce and the noodles and stir-fry for a final 2 minutes until everything is piping hot and coated in the sauce. Serve immediately.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: 'Leftovers — miso paste keeps in the fridge for up to 3 months. Use in glazes, marinades and salad dressings.',
    source_url: '',
    tags: ['vegan', 'quick', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Balsamic Blueberry, Brie & Cavolo Nero Toasties',
    description: 'A grown-up toasted sandwich layering wilted cavolo nero, ripe brie and balsamic-poached blueberries on sourdough.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Blueberries', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Balsamic vinegar', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Rosemary', quantity: 1, unit: 'bunch' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Cavolo nero', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Sourdough bread (large slices)', quantity: 4, unit: 'pieces' },
      { id: generateId(), name: 'Unsalted butter', quantity: 15, unit: 'g' },
      { id: generateId(), name: 'Wholegrain mustard', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Ripe brie', quantity: 100, unit: 'g' },
    ],
    steps: [
      'Put the blueberries, balsamic vinegar and a sprig of rosemary in a small saucepan. Heat gently until just bubbling, then remove from the heat and set aside. Meanwhile, heat the oil in a large frying pan over a medium heat. Add the peeled and bashed garlic, cavolo nero (stalks removed, leaves cut into strips), 1 tbsp water and a pinch of salt, and fry for about 3–4 minutes, turning regularly, until wilted. Tip onto a plate. Leave the pan ready for the sandwiches.',
      'Spread one side of each slice of bread with butter — these will be the outsides. Spread two of the inside slices with mustard, then layer up with the cavolo nero, sliced brie and finally the balsamic blueberries (discarding the rosemary). Top with the remaining slices of sourdough (butter on the outside) and press down lightly.',
      'Return the frying pan to a medium-high heat. Add the sandwiches, cover with a sheet of parchment, then top with another frying pan weighed down with 2 cans of beans. Fry for 3 minutes, then carefully turn and fry for another 3 minutes. Remove, cool for a minute, then halve and serve.',
    ],
    meal_type: ['lunch'],
    servings: 4,
    notes: "Cook's tip — poaching blueberries with balsamic brings out a richer flavour. Make a double batch and enjoy the leftovers over vanilla ice cream.",
    source_url: '',
    tags: ['vegetarian', 'sandwich', 'winter'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Chipotle Bean & Avocado Tacos',
    description: 'Quick, smoky black-bean tacos with lime-dressed red cabbage, avocado and melty cheddar. Ready in 20 minutes.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Vegetable oil', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Red onion', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Black beans (tinned)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Chipotle paste', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Red cabbage', quantity: 0.25, unit: 'pieces' },
      { id: generateId(), name: 'Lime', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Soft taco wraps', quantity: 6, unit: 'pieces' },
      { id: generateId(), name: 'Avocado', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Mature cheddar', quantity: 60, unit: 'g' },
    ],
    steps: [
      'Heat 1½ tbsp of the oil in a saucepan over a medium heat. Fry the finely chopped red onion, crushed garlic and a pinch of salt for 5 minutes until starting to soften. Add the drained and rinsed black beans, chipotle paste and 100 ml water and cook for another 5 minutes. Lightly crush the beans with a potato masher, leaving some whole, to create a thick sauce.',
      'Meanwhile, toss the finely shredded cabbage with the remaining ½ tbsp oil, the juice of ½ the lime and a pinch of salt. Warm the taco wraps according to pack instructions and divide between plates or a platter.',
      'Top the tacos with the beans, a little red cabbage, the sliced avocado and the grated cheese. Serve with the remaining lime cut into wedges.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: 'Leftovers — chipotle paste is great spread on chicken or salmon before grilling, or stirred into chilli con carne for a kick.',
    source_url: '',
    tags: ['vegetarian', 'quick', 'mexican', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Summery Pea & Basil Soup',
    description: "A vivid green soup of leeks, peas and basil, finished with crème fraîche. Great as a quick lunch with crusty bread and soft goat's cheese.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Leeks (large, ~400g total)', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garden peas (frozen)', quantity: 400, unit: 'g' },
      { id: generateId(), name: 'Vegetable stock (low-salt)', quantity: 750, unit: 'ml' },
      { id: generateId(), name: 'Basil', quantity: 12, unit: 'g' },
      { id: generateId(), name: 'Crème fraîche', quantity: 3, unit: 'tbsp' },
      { id: generateId(), name: 'Lemon', quantity: 0.5, unit: 'pieces' },
    ],
    steps: [
      'Heat the oil in a large frying pan over a medium heat. Add the trimmed and sliced leeks and a pinch of salt. Fry for 5–6 minutes until soft, then add the finely sliced garlic and fry for 2–3 minutes more. Add the peas and stock, bring to a simmer and cook for a further 3–4 minutes. Take off the heat and allow to cool for 5 minutes.',
      'Add the basil (about 30 leaves), crème fraîche and a squeeze of lemon juice (if using) to the pan; season. Whizz with a stick blender (or use a jug blender) until smooth. Taste and adjust the seasoning.',
      'Reheat if needed, then divide between bowls. Top with a little more crème fraîche, a few basil leaves and a grinding of black pepper.',
    ],
    meal_type: ['lunch'],
    servings: 4,
    notes: "Lemon juice is optional. The soup freezes for up to 3 months. Cook's tip — for a plant-based version, swap the crème fraîche for a non-dairy alternative (e.g. Oatly oat fraîche).",
    source_url: '',
    tags: ['vegetarian', 'soup', 'quick', 'batch-cook', 'summer'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Chickpea & Mushroom Pasta',
    description: 'A creamy, garlicky vegan pasta with chestnut mushrooms, chickpeas and a lemony nutritional-yeast cream sauce. Under 30 minutes.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Vegan butter', quantity: 50, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 4, unit: 'pieces' },
      { id: generateId(), name: 'Chestnut mushrooms', quantity: 250, unit: 'g' },
      { id: generateId(), name: 'Spaghetti', quantity: 350, unit: 'g' },
      { id: generateId(), name: 'Chickpeas (tinned)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Vegan cream cheese', quantity: 200, unit: 'g' },
      { id: generateId(), name: 'Nutritional yeast', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Unwaxed lemon', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Flat leaf parsley', quantity: 12, unit: 'g' },
    ],
    steps: [
      'Heat the vegan butter in a large frying pan over a medium-high heat. Add the crushed or finely grated garlic and fry for 1 minute. Add the thickly sliced mushrooms and a pinch of salt and fry for 2 minutes. Meanwhile, bring a large saucepan of salted water to the boil, add the pasta and cook for 1 minute less than pack instructions.',
      'Add the drained and rinsed chickpeas to the pan with the mushrooms and fry for 6–7 minutes until the mushrooms have released their liquid and are starting to colour. Meanwhile, mix the vegan cream cheese in a bowl with the nutritional yeast, lemon zest, some ground black pepper and 5 tbsp of cooking water from the pasta pan.',
      'Drain the pasta, reserving a little cooking water. Tip the pasta into the frying pan with the mushrooms and chickpeas. Add 3 tbsp of the reserved cooking water and stir over the heat. Take off the heat and stir through the creamy mixture and the juice of ½ the lemon. Season and toss with the chopped parsley before serving with extra black pepper.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Cook's tip — nutritional yeast has a deeply savoury, almost cheesy flavour. It's a savvy vegan alternative to parmesan or pecorino; use it in soups, risottos, dressings and dips.",
    source_url: '',
    tags: ['vegan', 'pasta', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: "Beetroot & Goat's Cheese Salad",
    description: "A make-a-meal-of-it salad layering roasted beetroot, beluga lentils, red chicory, fresh herbs and goat's cheese pearls.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Bunched beetroot', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Olive oil (extra virgin)', quantity: 5, unit: 'tbsp' },
      { id: generateId(), name: 'Cooked beluga lentils', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Balsamic vinegar', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Clear honey', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Red chicory', quantity: 140, unit: 'g' },
      { id: generateId(), name: 'Chives', quantity: 20, unit: 'g' },
      { id: generateId(), name: 'Mint', quantity: 12, unit: 'g' },
      { id: generateId(), name: "Goat's cheese pearls", quantity: 200, unit: 'g' },
    ],
    steps: [
      'Preheat the oven to 200°C (gas mark 6). In a bowl, toss the peeled beetroot wedges (cut into 2 cm pieces) with 1 tbsp of the oil, season and spread over a large baking tray. Roast for 20 minutes, then stir and roast for another 15 minutes. Add the lentils to the tray with 1 tbsp oil, season and roast for a final 10 minutes. Leave to cool for 5 minutes.',
      'Meanwhile, mix 2 tbsp of the oil in a large bowl with the balsamic vinegar and honey; season. Add the cooked beetroot and lentils, then stir in the roughly chopped chicory and most of the chopped chives and shredded mint. Stir through most of the goat\'s cheese.',
      'To serve, scatter over the remaining goat\'s cheese and herbs, then drizzle over the remaining 1 tbsp oil.',
    ],
    meal_type: ['lunch', 'dinner'],
    servings: 4,
    notes: 'Simple swap — beluga lentils can be replaced with brown or puy. To speed things up, use ready-cooked beetroot and just roast with the lentils for 10 minutes to warm through.',
    source_url: '',
    tags: ['vegetarian', 'salad', 'healthy'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Cheesy Lemon Spaghetti',
    description: 'A zingy weeknight winner ready in 15 minutes, made with just a handful of simple ingredients: butter, garlic, lemon and parmesan.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Spaghetti', quantity: 180, unit: 'g' },
      { id: generateId(), name: 'Unsalted butter', quantity: 40, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Unwaxed lemon', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Parmigiano Reggiano', quantity: 30, unit: 'g' },
      { id: generateId(), name: 'Flat leaf parsley', quantity: 2, unit: 'tbsp' },
    ],
    steps: [
      'Bring a large pan of salted water to the boil. Add the spaghetti and cook for 1 minute less than pack instructions.',
      'About 4 minutes before the spaghetti is ready, melt the butter in a large frying pan over a medium heat. When foaming, add the finely chopped garlic, half the lemon zest and a pinch of salt. Fry, stirring, for 2–3 minutes until the garlic is just golden.',
      'Drain the spaghetti and add to the frying pan with the juice of ½ the lemon and most of the parmesan. Toss together to emulsify the sauce, then add the chopped parsley. Serve with the remaining lemon zest and parmesan sprinkled over, and a few grindings of black pepper.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — add a sprinkle of chilli flakes for a burst of heat.",
    source_url: '',
    tags: ['vegetarian', 'pasta', 'quick', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Crispy Sea Bass with Lentils',
    description: 'Pan-fried sea bass on a bed of caramelised fennel, red onion and capers stirred through warm lentils. Super-speedy and gluten-free.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Fennel bulb (large, ~160g)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Red onion', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Nonpareille capers', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Lentils (tinned, in water)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Lemon', quantity: 0.5, unit: 'pieces' },
      { id: generateId(), name: 'Sea bass fillets', quantity: 2, unit: 'pieces' },
    ],
    steps: [
      'Heat 1 tbsp of the oil in a frying pan over a medium heat. Trim the fennel (reserving the fronds), remove the core and finely slice. Add to the pan with the finely sliced red onion, drained and rinsed capers, and a pinch of salt. Cook, stirring regularly, for 8–10 minutes until the vegetables are soft, lightly golden and caramelised.',
      'Add the drained and rinsed lentils to the pan with ½ tbsp oil and the juice of ¼ of the lemon. Heat through until piping hot, season and divide between plates.',
      'Wipe out the pan and return to the heat with the remaining ½ tbsp oil. Pat the sea bass dry with kitchen paper, score the skin 5–6 times and season all over. Fry, skin-side down, in the hot oil for 3 minutes until the skin is golden and releases easily from the pan. Turn and cook on the flesh side for 2–3 minutes, until opaque and flaking easily.',
      'Serve the sea bass with the lentils, reserved fennel fronds scattered on top, and the remaining ¼ of the lemon cut into wedges for squeezing over.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — these fillets can also be grilled (just make sure they're fully cooked and flake easily). Try serving with steamed veg and a coconut curry sauce for a different spin.",
    source_url: '',
    tags: ['fish', 'quick', 'midweek', 'gluten-free', 'healthy'],
    created_at: now,
    updated_at: now,
  },
];
