import type { Recipe } from '../types';
import { generateId } from './helpers';

const now = new Date().toISOString();

export const SEED_RECIPES: Recipe[] = [
  {
    id: generateId(),
    title: 'Gnocchi with Pesto & Green Beans',
    description: "A family-friendly tray-bake supper that's low on cost and cooked on a single tray.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sweet peppers', quantity: 3, unit: 'pieces' },
      { id: generateId(), name: 'Olive oil', quantity: 1.5, unit: 'tbsp' },
      { id: generateId(), name: 'Gnocchi', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Green beans', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Green pesto', quantity: 145, unit: 'g' },
    ],
    steps: [
      'Preheat the oven to 200°C (gas mark 6). Deseed the sweet peppers and cut into strips. Toss with 1 tbsp of the oil in a roasting tin and roast for 15 minutes.',
      'Put the gnocchi in a heatproof bowl and cover with just-boiled water from the kettle. Set aside for 3 minutes, then drain.',
      'Trim the ends of the green beans. Add the gnocchi and beans to the roasting tin, sprinkle over the remaining ½ tbsp oil, season, and roast for a further 10 minutes.',
      'As soon as the tin comes out of the oven, stir the pesto through the gnocchi, peppers and beans. Divide between plates with wild rocket and shavings of Parmigiano Reggiano, if liked.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Optional to serve: wild rocket leaves and Parmigiano Reggiano shavings. Cook's tip — swap the green pesto for red chilli pesto and add some cherry tomatoes for a different flavour.",
    source_url: '',
    tags: ['vegetarian', 'one-tray', 'quick', 'family-favourite'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Salmon & Avocado Noodles',
    description: 'A quick midweek bowl of egg noodles, salmon and avocado with a salty-sweet soy-ginger dressing.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Edamame beans (frozen)', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Salmon fillets', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Egg noodles', quantity: 275, unit: 'g' },
      { id: generateId(), name: 'Avocado', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Salad onions', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Soy sauce', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Mirin', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Maple syrup', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Toasted sesame oil', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Ginger', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Shichimi togarashi', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Preheat the grill to high. Cook the edamame beans according to pack instructions, drain and set aside.',
      'Make the soy-ginger dressing by mixing the soy sauce, mirin, maple syrup, sesame oil and grated ginger in a small bowl.',
      'Arrange the salmon, skin-side down, on a foil-lined baking tray. Spoon over 2 tsp of the dressing. Grill for 6–8 minutes, until the fish is opaque and flakes easily.',
      'Meanwhile, cook the egg noodles according to pack instructions and divide between shallow bowls.',
      'Slice the avocado and finely slice the salad onions. Top each bowl with a salmon fillet, the edamame beans, avocado and salad onions. Spoon over the remaining dressing and sprinkle with shichimi togarashi, if liked.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — Mirin is a Japanese rice wine, similar to sake but lower in alcohol and sweeter. If you don't have any, substitute a splash of sherry or rice vinegar. The shichimi togarashi is optional.",
    source_url: '',
    tags: ['quick', 'fish', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Smoky Barbecue Beans, Sweet Potato Fries & Guac',
    description: 'Smoky tomatoey beans with crispy sweet potato wedges and fresh guacamole. Vegan and low carbon impact.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sweet potato', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Garlic cloves', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Onion', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Courgette', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Haricot beans', quantity: 240, unit: 'g' },
      { id: generateId(), name: 'Smoked paprika', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Chilli flakes', quantity: 1, unit: 'tsp' },
      { id: generateId(), name: 'Passata', quantity: 200, unit: 'g' },
      { id: generateId(), name: 'Balsamic vinegar', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Maple syrup', quantity: 2, unit: 'tsp' },
      { id: generateId(), name: 'Fresh coriander', quantity: 1, unit: 'bunch' },
      { id: generateId(), name: 'Lime', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Avocado', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Preheat the oven to 220°C (fan 200°C / gas mark 7) and line a baking tray with parchment. Cut the sweet potato into 2 cm thick wedges, toss with ½ tbsp oil and a pinch of salt and pepper on the tray, and roast for 20–25 minutes until soft and golden.',
      'Meanwhile, finely chop or crush the garlic. Finely slice three-quarters of the onion and finely dice the rest. Thinly slice the courgette into half-moons. Drain and rinse the haricot beans.',
      'Heat a large saucepan with the remaining ½ tbsp oil over medium heat. Add the garlic and sliced onion and cook for 3 minutes. Season, then add the courgette, paprika and chilli flakes (to taste) and cook for a further 3 minutes.',
      'Add the beans, passata, balsamic vinegar and maple syrup. Simmer for 8–10 minutes, until the sauce thickens.',
      'Roughly chop the coriander and halve the lime. Mash the avocado in a small bowl, then mix in the diced onion, coriander and a squeeze of lime juice. Season to taste.',
      'Serve the barbecue beans with the guacamole and sweet potato wedges. Garnish with the remaining lime, cut into wedges.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: 'Halve the ingredients to serve 1. The dish is vegan as written.',
    source_url: '',
    tags: ['vegan', 'midweek', 'low-carbon'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Chilli Crab & Toasted Corn Linguine',
    description: 'Speedy pasta with charred sweetcorn, mild red chilli, parsley and crab — ready in 20 minutes.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Sweetcorn (frozen)', quantity: 160, unit: 'g' },
      { id: generateId(), name: 'Dried linguine', quantity: 180, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 2.5, unit: 'tbsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Mild red chilli', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Flat leaf parsley', quantity: 2, unit: 'tbsp' },
      { id: generateId(), name: 'Crab meat (50/50 white & brown)', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Unwaxed lemon', quantity: 0.5, unit: 'pieces' },
    ],
    steps: [
      'Heat a medium-large nonstick frying pan over a high heat. Add the corn and dry-fry, stirring regularly, for 5 minutes until lightly charred in places and piping hot. Tip into a bowl and set aside. Meanwhile, cook the pasta in a large saucepan of salted boiling water for 1 minute less than the pack instructions.',
      'Five minutes before the pasta is ready, return the frying pan to a medium heat with the oil, finely chopped garlic, deseeded and finely chopped chilli, and finely chopped parsley. Cook gently for 2 minutes, then stir in the crab and warm everything through.',
      'Scoop out a mugful of the pasta cooking water, then drain the pasta and add to the frying pan with a glug of the cooking water. Toss over the heat with the charred corn and the lemon zest and juice until piping hot. Divide between plates and serve straight away.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — 50/50 crab is a mix of white and brown crabmeat. If you prefer a milder crab flavour, use all-white meat.",
    source_url: '',
    tags: ['quick', 'fish', 'pasta'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Salmon & Watercress Spaghetti',
    description: 'A tub of watercress tzatziki creates an almost instant sauce for this speedy pasta dish.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Dried spaghetti', quantity: 180, unit: 'g' },
      { id: generateId(), name: 'Purple sprouting broccoli', quantity: 230, unit: 'g' },
      { id: generateId(), name: 'Scottish poached salmon fillets', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Watercress tzatziki', quantity: 170, unit: 'g' },
      { id: generateId(), name: 'Unwaxed lemon', quantity: 0.5, unit: 'pieces' },
      { id: generateId(), name: 'Parmigiano Reggiano', quantity: 10, unit: 'g' },
    ],
    steps: [
      'Bring a large saucepan of salted water to the boil. Add the spaghetti and simmer for a minute less than pack instructions, adding the broccoli (cut into 3–4 cm pieces) to the pan for the final 3 minutes of cooking time. Before draining, scoop out a mugful of the cooking water. Meanwhile, flake the salmon and remove the skin.',
      'Tip the drained pasta back into the pan (off the heat). Add the flaked salmon, tzatziki, lemon zest and a squeeze of juice, the cheese and 3 tbsp of the pasta cooking water. Toss together with tongs to combine and serve with extra grated cheese.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: 'Boost fibre by using wholewheat spaghetti and add some frozen peas with the broccoli, if liked.',
    source_url: '',
    tags: ['quick', 'fish', 'pasta', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Cheddar & Leek Orzotto',
    description: "A pleasingly simple twist on risotto that's quicker to make but just as gratifying as the original.",
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Leek (large, ~250g)', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Unsalted butter', quantity: 20, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Garlic cloves', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Orzo pasta', quantity: 150, unit: 'g' },
      { id: generateId(), name: 'Chicken or vegetable stock', quantity: 500, unit: 'ml' },
      { id: generateId(), name: 'Petits pois (frozen)', quantity: 100, unit: 'g' },
      { id: generateId(), name: 'Mature cheddar', quantity: 80, unit: 'g' },
    ],
    steps: [
      'Halve the leek lengthways, then halve again into quarters and finely slice. Heat the butter and olive oil in a medium-large saucepan over a medium-high heat. Add the leek, finely chopped garlic and a pinch of salt and cook, stirring regularly, for 5 minutes until soft but without any colour.',
      'Add the orzo to the pan and stir through the leek. Cook, stirring, for 2 minutes. Add 400 ml of the stock, bring to the boil, then reduce to a gentle simmer. Cook for about 4 minutes, stirring regularly, then stir in the peas. Cook for another 4 minutes, adding more stock if it looks dry (it should be a loose consistency). The orzo is ready when tender but with just a little bite.',
      'Take off the heat and stir in half of the cheddar, then let stand for 2 minutes. Sprinkle the remaining cheese over the top and serve with a grinding of black pepper.',
    ],
    meal_type: ['dinner'],
    servings: 2,
    notes: "Cook's tip — Use fresh stock if you can; its flavour really comes through in the orzotto.",
    source_url: '',
    tags: ['vegetarian', 'quick', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Courgette, Chickpea & Feta Pasta',
    description: 'A great-value, great-tasting weeknight pasta — the chickpeas pack in fibre and protein.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Olive oil', quantity: 3, unit: 'tbsp' },
      { id: generateId(), name: 'Courgettes', quantity: 500, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 3, unit: 'pieces' },
      { id: generateId(), name: 'Chifferi rigati (or other short) pasta', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Chickpeas (tinned)', quantity: 1, unit: 'tin' },
      { id: generateId(), name: 'Lemon', quantity: 1, unit: 'pieces' },
      { id: generateId(), name: 'Chilli flakes', quantity: 0.5, unit: 'tsp' },
      { id: generateId(), name: 'Feta', quantity: 120, unit: 'g' },
      { id: generateId(), name: 'Basil', quantity: 1, unit: 'bunch' },
    ],
    steps: [
      'Heat the oil in a large frying pan over a medium-high heat. Add the thinly sliced courgettes and sliced garlic with a large pinch of salt. Fry for 10–12 minutes until tender and golden.',
      'Once the courgettes are turning golden, bring a large pan of salted water to the boil. Add the pasta and cook according to pack instructions. Scoop out a mugful of cooking water, then drain.',
      'Meanwhile, add the drained and rinsed chickpeas to the courgette pan, turn the heat up to high and fry for another 5 minutes. Stir in the drained pasta, 3 tbsp pasta cooking water, the lemon zest and the juice of ½ the lemon, and the chilli flakes. Toss together. Take off the heat and stir through the crumbled feta and shredded basil (if using). Season and serve immediately with freshly ground black pepper.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Cook's tip — chilli flakes vary in heat; add a little, taste, then add more. Sub in paprika to skip the heat. Basil is optional.",
    source_url: '',
    tags: ['vegetarian', 'pasta', 'midweek'],
    created_at: now,
    updated_at: now,
  },
  {
    id: generateId(),
    title: 'Conchiglie with Mushrooms & Spinach',
    description: 'A veg-packed pasta bake with porcini, chestnut mushrooms, wilted spinach and a creamy parmesan sauce.',
    image: undefined,
    ingredients: [
      { id: generateId(), name: 'Dried porcini mushrooms', quantity: 15, unit: 'g' },
      { id: generateId(), name: 'Spinach (ready-washed)', quantity: 235, unit: 'g' },
      { id: generateId(), name: 'Conchiglie rigate pasta', quantity: 300, unit: 'g' },
      { id: generateId(), name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { id: generateId(), name: 'Echalion shallots', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Chestnut mushrooms', quantity: 250, unit: 'g' },
      { id: generateId(), name: 'Garlic cloves', quantity: 2, unit: 'pieces' },
      { id: generateId(), name: 'Double cream', quantity: 6, unit: 'tbsp' },
      { id: generateId(), name: 'Parmigiano Reggiano', quantity: 60, unit: 'g' },
    ],
    steps: [
      'Preheat the grill to high and put an oven shelf in the top third of the oven. Boil a kettle. Put the dried porcini in a heatproof bowl and cover with 300 ml just-boiled water; set aside. Put the spinach in a large mixing bowl and pour over enough just-boiled water to wilt. Drain through a sieve, rinse under the cold tap, squeeze out the excess liquid and pat dry with kitchen paper.',
      'Bring a large saucepan of water to the boil and cook the pasta for 1 minute less than pack instructions. In a separate large, shallow casserole, heat the oil over medium-high heat. Add the finely diced shallots, sliced chestnut mushrooms, crushed garlic and a pinch of salt. Cover with a lid and sweat for 5 minutes, stirring occasionally. Uncover and fry for another 5 minutes.',
      'Lift the porcini out of the soaking liquid, squeezing any excess back into the bowl (reserve the liquid). Finely chop the porcini and roughly chop the spinach, then stir both into the casserole. Add 200 ml of the mushroom soaking liquid (leaving any sediment behind) and the cream. Drain the pasta and tip into the casserole with ⅔ of the parmesan. Season and stir together over the heat for 1 minute.',
      'Scatter over the remaining cheese and grill for 2–3 minutes until golden. Stand for 2 minutes before serving in bowls.',
    ],
    meal_type: ['dinner'],
    servings: 4,
    notes: "Cook's tip — Blanching and drying the spinach first stops the sauce becoming watery.",
    source_url: '',
    tags: ['vegetarian', 'pasta'],
    created_at: now,
    updated_at: now,
  },
];
